### ISSUE TITLE
AWX sync not possible - Illegal filename ..

### ISSUE THREAD

**Issue by ropitz-wago** [willshersystems/ansible-sshd#259] opened 2023-10-09 09:04 UTC
After an update to the newest AWX execution environment we can't sync your repo via requirements.txt in a project anymore.

Error Message:

    - extracting willshersystems.sshd to /var/lib/awx/.../stage/requirements_roles/willshersystems.sshd
    [WARNING]: Illegal filename &apos;..&apos;: &apos;..&apos; is not allowed
    ERROR! Unexpected Exception, this is probably a bug: join() missing 1 required positional argument: &apos;a&apos;

Solution:
We forked you repo and deleted the symlink and it works now.

    ansible-sshd/tests/roles$ ls -l
    lrwxrwxrwx 1 root root 6  9. Okt 10:55 ansible-sshd -> ../../

**Comment by jose-d** [comment] 2023-10-09 10:04
as noted here, https://github.com/willshersystems/ansible-sshd/issues/176#issuecomment-1677474596, this role is part of collection.

From my knowledge of AWX it's cleaner to use the collection instead of manually installing roles.

**Comment by hv15** [comment] 2023-10-11 07:54
@ropitz-wago what version of ansible are you using, with ansible-core 2.15.5 symlinks in roles are no longer allowed, see https://github.com/ansible/ansible/blob/v2.15.5/changelogs/CHANGELOG-v2.15.rst#id20.

**Comment by ropitz-wago** [comment] 2023-10-11 10:00
@hv15, I know, that's why I opened the issue. In this role (repo) there is a symlink and it's unuseable.

**Comment by richm** [comment] 2023-10-11 13:16
I think the problem is that the symlink causes a recursive path.  The tests/roles symlink is needed because of the way we run integration tests from the `tests/` directory.  We had the same problem with other linux-system-roles.  The solution is to create a directory `tests/roles/ansible-sshd/` and in this directory create symlinks to the role subdirectories - `../../../tasks/`, `../../../defaults/`, `../../../vars`, etc.  That way, the symlinks won't be recursive.

**Comment by mattwillsher** [comment] 2023-10-20 11:48
Closing in favour of #260 . Thank you for the report.

**Closed by mattwillsher** 2023-10-20 11:48 UTC
