### ISSUE TITLE
not reloading with default sshd_allow_reload value

### ISSUE THREAD

**Issue by ianheggie** [willshersystems/ansible-sshd#22] opened 2015-06-28 08:21 UTC
Thanks for a great plugin - I am impressed with how you set it up. I had trouble in getting it to reload though.

In tasks/main.yml you just have `when: sshd_manage_service` which runs, in handlers/main.yml you have `when: sshd_allow_reload == True` which gets skipped.

If I explicitly set `sshd_allow_reload: True` then the problem goes away.

I also noticed neither `OS is supported` nor `Register that this role has run` tasks are run if you restrict to `sshd` tag - was that deliberate?

DETAILS:

With settings:
```
sshd_Port: 234
sshd:
  PermitRootLogin: no
```
I would see output like the following indicating that the reload_sshd was skipped:
```
TASK: [willshersystems.sshd | Set OS dependent variables] ********************* 
ok: [lodge] => (item=/home/ianh/Projects/Acme/beaver/outfit/roles/willshersystems.sshd/vars/Ubuntu_14.yml)
ok: [outfit-test] => (item=/home/ianh/Projects/Acme/beaver/outfit/roles/willshersystems.sshd/vars/Ubuntu_14.yml)

TASK: [willshersystems.sshd | OS is supported] ******************************** 
ok: [lodge]
ok: [outfit-test]

TASK: [willshersystems.sshd | Installed] ************************************** 
ok: [outfit-test] => (item=openssh-server)
ok: [lodge] => (item=openssh-server)
ok: [outfit-test] => (item=openssh-sftp-server)
ok: [lodge] => (item=openssh-sftp-server)

TASK: [willshersystems.sshd | Run directory] ********************************** 
ok: [lodge]
ok: [outfit-test]

TASK: [willshersystems.sshd | Configuration] ********************************** 
changed: [outfit-test]
changed: [lodge]

TASK: [willshersystems.sshd | Service enabled and running] ******************** 
ok: [lodge]
ok: [outfit-test]

TASK: [willshersystems.sshd | Register that this role has run] **************** 
ok: [lodge]
ok: [outfit-test]

NOTIFIED: [willshersystems.sshd | check_and_reload_sshd] ********************** 
changed: [outfit-test]
changed: [lodge]

NOTIFIED: [willshersystems.sshd | reload_sshd] ******************************** 
skipping: [lodge]
skipping: [outfit-test]
```
When I added
```
sshd_allow_reload: True
```
(And altered the port manually in /etc/ssh/sshd_config from 234 back to 22 on lodge), I then got as expected:
```
NOTIFIED: [willshersystems.sshd | check_and_reload_sshd] ********************** 
changed: [lodge]

NOTIFIED: [willshersystems.sshd | reload_sshd] ******************************** 
changed: [lodge]
```
And `netstat -an | egrep 234` reported the port was open on lodge.

I noted that `Service enabled and running` was not skipped so it appears sshd_manage_service is true even though is behaving as false.

**Comment by mattwillsher** [comment] 2015-06-28 08:35
Hi Ian,

The reload issues are regressions from the addition of sshd_allow_reload in #16. Looking at the code, the quoting of sshd_allow_reload: "{{ sshd_manage_service }}" may be the problem.

The tag issue must be a longer standing defect - its not by design, I don't think.

**Comment by ianheggie** [comment] 2015-06-28 08:44
thanks for the prompt reply

**Comment by mattwillsher** [comment] 2015-06-28 09:22
#23 has just been merged which fixes both issues. I've a bit of documentation to update then I'll release 0.3.1

**Closed by mattwillsher** 2015-06-28 09:22 UTC
Labels: bug

**Comment by mattwillsher** [comment] 2015-06-28 09:34
0.3.1 is now up on Galaxy
