### ISSUE TITLE
subsystem appears to be ignored

### ISSUE THREAD

**Issue by grimreaper** [willshersystems/ansible-sshd#119] opened 2019-11-25 09:23 UTC
With the following config
```
- src: willshersystems.sshd
  version: v0.8.1
```

```
sshd:
  Compression: yes
  ListenAddress:
    - "0.0.0.0"
    - "::"
  AllowAgentForwarding: yes
  AllowGroups: ssh_allowed
  AuthenticationMethods: publickey
  PermitRootLogin: no
  Port: 22
  UseDNS: no
  Subsystem: "sftp internal-sftp"
```
I get the following sshd_config
```
# Ansible managed
Port 22
ListenAddress 0.0.0.0
ListenAddress ::
AllowAgentForwarding yes
AllowGroups ssh_allowed
AuthenticationMethods publickey
Compression yes
PermitRootLogin no
UseDNS no
```

Note the lack of "Subsystem" in the second block. Am I missing something?

**Comment by zanthorn** [comment] 2020-04-14 22:06
`sshd_sftp_server: internal-sftp` works. 

It wasn't the most obvious but I found this in `defaults/main.yml`:
```### VARS DEFAULTS
### The following are defaults for OS specific configuration in var files in
### this role. They should not be set directly by role users. If you really
### need to override them, use the corresponding, unprefixed variables (eg
### `sshd_packages` to override __sshd_packages).
__sshd_packages: []
__sshd_config_owner: root
__sshd_config_group: root
__sshd_config_mode: "0600"
__sshd_config_file: /etc/ssh/sshd_config
__sshd_binary: /usr/sbin/sshd
__sshd_service: sshd

### These variables are used by role internals and should not be used.
__sshd_sftp_server: /usr/lib/openssh/sftp-server
__sshd_defaults: {}
__sshd_os_supported: no```

**Comment by Jakuje** [comment] 2020-09-23 12:25
I tried with current version and I was not able to reproduce the issue.

I also submitted a PR with the test doing exactly what you describe and checking that the option is effective and generated file contains this option. Not sure what could have gone wrong:

https://github.com/willshersystems/ansible-sshd/pull/134/files#diff-d14880d5c85a1b0ba747f58c776b68ff

**Comment by mattwillsher** [comment] 2020-10-03 14:44
Closing as can't be reproduced with current version. Thanks all.

**Closed by mattwillsher** 2020-10-03 14:44 UTC
Labels: bug, cantreproduce
